### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by cksidharthan** [hirokisan/bybit#10]
some of the tests are failing in the code
maybe checking the return code and return message will suffice and will make the tests more robust?
also need to specify how much usdt should be present in the account before running the test

**Comment by hirokisan** [comment]
>maybe checking the return code and return message will suffice and will make the tests more robust?

As a matter of fact, I didn't think much about it.

To begin with, I prepared the tests to understand the change in response.

But, I agree with you in terms of testing for CI.

---

As for testing for CI, it may be good to have tests for clients like below ref.

ref: https://github.com/google/go-github/tree/master/github

On the other hand, in order to understand the change in response, it may be a good idea to separate the directory as shown below so that we can check it easily.

ref: https://github.com/google/go-github/tree/master/test

**Comment by hirokisan** [comment]
generally completed with the above PRs
